[tool.poetry]
name = "the-supa-awesome-compiler"
version = "0.1.0"
description = ""
authors = ["Anas Badr <anasihabezmc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
